#!/usr/bin/env python
# coding: utf-8

# In[1]:


# -*- coding: utf-8 -*-
"""leukemia

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-lXFSx-rTmFClJ2XkECCFX21dZ4r7MdT
"""

import cv2
import pytesseract
import re
import numpy as np
import pandas as pd
import joblib
import easyocr

pytesseract.pytesseract.tesseract_cmd = r"C:/Program Files/Tesseract-OCR/tesseract.exe"

def predict_image(path):

    keywords = ['HB', 'WBCs', 'Platelet Count',
                'Basophils', 'Eosinphils', 'Gender']
    try:

        try:

            img = cv2.imread(path)
            # Convert the image to gray scale
            img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

            ocr_output = pytesseract.image_to_string(img_gray)
            dictionary = {}
            for line in ocr_output.split('\n'):
                if 'MCHC' in line:
                    continue

                for keyword in keywords:
                    try:
                        try:
                            if re.search(keyword, line, re.IGNORECASE):
                                if '=' in line:
                                    list_ = line.split('=')
                                    list_ = str(list_)
                                    result = re.search(
                                        '\d+\.{0,1}\d*', list_).group()
                                    dictionary[keyword] = float(result)
                                    break
                                elif ':' in line:
                                    list_ = line.split(':')
                                    list_ = str(list_)
                                    result = re.search(
                                        '\d+\.{0,1}\d*', list_).group()
                                    dictionary[keyword] = float(result)
                                    break

                            elif re.search('Male', line):
                                dictionary['Gender'] = 'Male'
                                break

                            elif re.search('Female', line):
                                dictionary['Gender'] = 'Female'
                                break
                        except:
                            if re.search(keyword, line, re.IGNORECASE):
                                list_ = str(line.split())
                                result = re.search(
                                    '\d+\.{0,1}\d*', list_).group()
                                dictionary[keyword] = float(result)
                                break
                    except:
                        continue

            model_acute_l = joblib.load(
                'DocTork-master/ML_Model/API_2/CV_ML_model_images/leukemia/Model/RandomForestModel(AcuteL-m,f).h5')
            model_cml = joblib.load(
                'DocTork-master/ML_Model/API_2/CV_ML_model_images/leukemia/Model/RandomForestModel(CML-m,f).h5')
            features = list(model_acute_l.feature_names_in_) + \
                list(model_cml.feature_names_in_)
            features.pop(3)  # Delete Duplicated Gender_Male from Feature List
            features.pop(3)  # Delete Duplicated Hemoglobin from Feature List
            features.pop(3)  # Delete Duplicated Platelets from Feature List
            data_dic = {}
            data_dic[features[0]] = dictionary['HB']
            data_dic[features[1]] = dictionary['WBCs']
            data_dic[features[2]] = dictionary['Platelet Count']
            data_dic[features[3]] = dictionary['Basophils']
            data_dic[features[4]] = dictionary['Eosinphils']
            if dictionary['Gender'].startswith('F'):
                data_dic[features[5]] = 0
            elif dictionary['Gender'].startswith('M'):
                data_dic[features[5]] = 1

            custom_data = pd.DataFrame(data=[data_dic])
            # print('-----'*10)
            # print('Your Input :\n',custom_data)
            # print('-----'*10)
            pred_acute_l = model_acute_l.predict(
                custom_data[list(model_acute_l.feature_names_in_)])[0]
            pred_cml = model_cml.predict(
                custom_data[list(model_cml.feature_names_in_)])[0]
            if pred_cml == pred_acute_l:
                # As predication of two models is same
                # Two models have predicted Good as Label
                # print('Based on Your Complete Blood Count (CBC) :')
                # print('------'*10)
                # print('\t There is No Probability of Acute Leukmia and Chronic Myelogenous Leukemia (CML) ')
                output = 'Good'

            elif pred_cml == 'CML' and pred_acute_l == 'Acute L':
                # As predication of two models is different
                # One model has predicted CML as Label
                # Other model has  predicted Acute L as Label
                # print('Based on Your Complete Blood Count (CBC) :')
                # print('-----'*10)
                # print(
                # '''
                # There is Probability of Acute Leukmia and Chronic Myelogenous Leukemia (CML) :
                #     >> As Your ['Hemoglobin' , 'WBCs', 'Platelets', 'Basophilis','Eosinophilia'] may be not in normal ranges
                # '''
                #   )
                output = 'Acute  L or CML'

            elif pred_cml == 'CML' and pred_acute_l == 'Good':
                # As predication of two models is different
                # One model has predicted CML as Label
                # Other model has  predicted Good as Label
                # print('Based on Your Complete Blood Count (CBC) :')
                # print('-----'*10)
                # print(
                # '''
                # There is Probability of Chronic Myelogenous Leukemia (CML) :
                #     >> As Your ['Hemoglobin', 'Platelets','Basophilis','Eosinophilia'] may be not in normal ranges
                # '''
                # )
                output = 'CML'

            elif pred_cml == 'Good' and pred_acute_l == 'Acute L':
                # As predication of two models is different
                # One model has predicted Good as Label
                # Other model has  predicted Acute L as Label
                # print('Based on Your Complete Blood Count (CBC) :')
                # print('-----'*10)
                # print(
                #   '''
                # There is Probability of Acute Leukmia :
                #    >> As Your ['Hemoglobin' , 'WBCs', 'Platelets'] may be not in normal ranges
                # '''
                # )
                output = 'Acute L'

            correct_predication_name = {
                'Anemia': 'Normal Anemia',
                'Good': 'Normal ',
                'Micro': 'Microcytic Anemia',
                          'Macro': 'Macrocytic Anemia',
                          'CML': 'Chronic Myelogenous Leukemia',
                          'Acute L': 'Acute Lymphoblastic Leukemia',
                          'HyperTyroid':  'Hyperthyroidism',
                          'Hypothyroid': 'Hypothyroidism',
                          'Other Thyroid Abnormalities':  'Other Thyroid Abnormalities',
                          'Normal':  'Normal ',
                          'Hyperuricosuria (Gout)': 'Hyperuricemia (Gout)',
                          'Hypouricosuria ':  'Hypouricemia',
                          'Jaundice':  'Jaundice',
                          'Diabetic': 'Diabetes',
                          'Pre Diabetic': 'Prediabetes',
                          'Hypoglycemia': 'Hypoglycemia',
                          'Prostatic_Cancer':  'Prostatic Cancer',
                          'Rheumatiod_Arthities': 'Rheumatoid Arthritis',
                          'Hypoparathyroid': 'Hypoparathyroidism',
                          'Another Disease':  'Another Disease',
                          'Hyperparathyroid': 'Hyperparathyroidism',
                          'Acute  L or CML':  'Acute Lymphoblastic Lekumia and Chronic Myelogenous Lekumia',
                          'Good':  'Normal',
                          'Normal': 'Normal'}

            patient_output_disease = correct_predication_name[output]
            return patient_output_disease

        except:
            # this needs to run only once to load the model into memory
            reader = easyocr.Reader(['en'], gpu=False)
            img = path
            output = reader.readtext(img, detail=1)
            dictionary = {}
            for i in output:
                probability = i[-1]

                if probability >= 0.6:
                    text = i[1]

                if 'MCHC' in text:
                    continue

                for keyword in keywords:
                    try:
                        try:
                            if re.search(keyword, text, re.IGNORECASE):
                                if '=' in text:
                                    list_ = text.split('=')
                                    list_ = str(list_)
                                    result = re.search(
                                        '\d+\.{0,1}\d*', list_).group()
                                    dictionary[keyword] = float(result)
                                    break
                                elif ':' in text:
                                    list_ = text.split(':')
                                    list_ = str(list_)
                                    result = re.search(
                                        '\d+\.{0,1}\d*', list_).group()
                                    dictionary[keyword] = float(result)
                                    break

                            elif re.search('Male', line):
                                dictionary['Gender'] = 'Male'
                                break

                            elif re.search('Female', line):
                                dictionary['Gender'] = 'Female'
                                break
                        except:
                            if re.search(keyword, text, re.IGNORECASE):
                                list_ = str(text.split())
                                result = re.search(
                                    '\d+\.{0,1}\d*', list_).group()
                                dictionary[keyword] = float(result)
                                break
                    except:
                        continue
            model_acute_l = joblib.load(
                'DocTork-master/ML_Model/API_2/CV_ML_model_images/leukemia/Model/RandomForestModel(AcuteL-m,f).h5')
            model_cml = joblib.load(
                'DocTork-master/ML_Model/API_2/CV_ML_model_images/leukemia/Model/RandomForestModel(CML-m,f).h5')
            features = list(model_acute_l.feature_names_in_) + \
                list(model_cml.feature_names_in_)
            features.pop(3)  # Delete Duplicated Gender_Male from Feature List
            features.pop(3)  # Delete Duplicated Hemoglobin from Feature List
            features.pop(3)  # Delete Duplicated Platelets from Feature List
            data_dic = {}
            data_dic[features[0]] = dictionary['HB']
            data_dic[features[1]] = dictionary['WBCs']
            data_dic[features[2]] = dictionary['Platelet Count']
            data_dic[features[3]] = dictionary['Basophils']
            data_dic[features[4]] = dictionary['Eosinphils']
            if dictionary['Gender'].startswith('F'):
                data_dic[features[5]] = 0
            elif dictionary['Gender'].startswith('M'):
                data_dic[features[5]] = 1
            custom_data = pd.DataFrame(data=[data_dic])
            # print('-----'*10)
            # print('Your Input :\n',custom_data)
            # print('-----'*10)
            pred_acute_l = model_acute_l.predict(
                custom_data[list(model_acute_l.feature_names_in_)])[0]
            pred_cml = model_cml.predict(
                custom_data[list(model_cml.feature_names_in_)])[0]
            if pred_cml == pred_acute_l:
                # As predication of two models is same
                # Two models have predicted Good as Label
                # print('Based on Your Complete Blood Count (CBC) :')
                # print('------'*10)
                # print('\t There is No Probability of Acute Leukmia and Chronic Myelogenous Leukemia (CML) ')
                output = 'Good'

            elif pred_cml == 'CML' and pred_acute_l == 'Acute L':
                # As predication of two models is different
                # One model has predicted CML as Label
                # Other model has  predicted Acute L as Label
                # print('Based on Your Complete Blood Count (CBC) :')
                # print('-----'*10)
                # print(
                # '''
                # There is Probability of Acute Leukmia and Chronic Myelogenous Leukemia (CML) :
                #     >> As Your ['Hemoglobin' , 'WBCs', 'Platelets', 'Basophilis','Eosinophilia'] may be not in normal ranges
                # '''
                #   )
                output = 'Acute  L or CML'

            elif pred_cml == 'CML' and pred_acute_l == 'Good':
                # As predication of two models is different
                # One model has predicted CML as Label
                # Other model has  predicted Good as Label
                # print('Based on Your Complete Blood Count (CBC) :')
                # print('-----'*10)
                # print(
                # '''
                # There is Probability of Chronic Myelogenous Leukemia (CML) :
                #     >> As Your ['Hemoglobin', 'Platelets','Basophilis','Eosinophilia'] may be not in normal ranges
                # '''
                # )
                output = 'CML'

            elif pred_cml == 'Good' and pred_acute_l == 'Acute L':
                # As predication of two models is different
                # One model has predicted Good as Label
                # ther model has  predicted Acute L as Label
                # print('Based on Your Complete Blood Count (CBC) :')
                # print('-----'*10)
                # print(
                #   '''
                # There is Probability of Acute Leukmia :
                #    >> As Your ['Hemoglobin' , 'WBCs', 'Platelets'] may be not in normal ranges
                # '''
                # )
                output = 'Acute L'

            correct_predication_name = {
                'Anemia': 'Normal Anemia',
                'Good': 'Normal ',
                'Micro': 'Microcytic Anemia',
                          'Macro': 'Macrocytic Anemia',
                          'CML': 'Chronic Myelogenous Leukemia',
                          'Acute L': 'Acute Lymphoblastic Leukemia',
                          'HyperTyroid':  'Hyperthyroidism',
                          'Hypothyroid': 'Hypothyroidism',
                          'Other Thyroid Abnormalities':  'Other Thyroid Abnormalities',
                          'Normal':  'Normal ',
                          'Hyperuricosuria (Gout)': 'Hyperuricemia (Gout)',
                          'Hypouricosuria ':  'Hypouricemia',
                          'Jaundice':  'Jaundice',
                          'Diabetic': 'Diabetes',
                          'Pre Diabetic': 'Prediabetes',
                          'Hypoglycemia': 'Hypoglycemia',
                          'Prostatic_Cancer':  'Prostatic Cancer',
                          'Rheumatiod_Arthities': 'Rheumatoid Arthritis',
                          'Hypoparathyroid': 'Hypoparathyroidism',
                          'Another Disease':  'Another Disease',
                          'Hyperparathyroid': 'Hyperparathyroidism',
                          'Acute  L or CML':  'Acute Lymphoblastic Lekumia and Chronic Myelogenous Lekumia',
                          'Good':  'Normal',
                          'Normal': 'Normal'}

            patient_output_disease = correct_predication_name[output]
            return patient_output_disease

    except:
        print('Your uploaded image can\'t be detected')
        print('-----'*10)
        model_acute_l = joblib.load(
            'DocTork-master/ML_Model/API_2/CV_ML_model_images/leukemia/Model/RandomForestModel(AcuteL-m,f).h5')
        model_cml = joblib.load(
            'DocTork-master/ML_Model/API_2/CV_ML_model_images/leukemia/Model/RandomForestModel(CML-m,f).h5')
        features = list(model_acute_l.feature_names_in_) + \
            list(model_cml.feature_names_in_)
        features.pop(3)  # Delete Duplicated Gender_Male from Feature List
        features.pop(3)  # Delete Duplicated Hemoglobin from Feature List
        features.pop(3)  # Delete Duplicated Platelets from Feature List
        return 'Your uploaded image can\'t be detected\n \t Enter Manually the Following Please : ', features[:-1]
