# -*- coding: utf-8 -*-
"""diabetes_pdf

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-lXFSx-rTmFClJ2XkECCFX21dZ4r7MdT
"""

from tika import parser
import re
import joblib
import pandas as pd
import numpy as np
import PyPDF2


def predict_pdf(path):
    keywords = ['A1C', 'FPG', 'HRPP']
    pdf = path
    try:
        try:
            custom_values_list = []
            for x in keywords:
              # Open the PDF file in binary mode
                with open(path, 'rb') as pdf_file:
                    # Create a PDF reader object
                    pdf_reader = PyPDF2.PdfReader(pdf_file)

                    # Get the first page of the PDF file
                    page = pdf_reader.pages[0]

                    # Extract the text from the page
                    text = page.extract_text()
                    for i in text.split('\n'):
                        i = i.replace(' ', '')
                        if re.search(x, i, re.IGNORECASE):
                            # Our chosen sentence
                            # Converting our little sentence to a list and splitting it into words to finally extract the needed number.
                            if ('A1C' in x) or ('HRPP' in x):

                                list_ = list(i.split())
                                list_ = str(list_)
                                try:
                                    result = re.findall(
                                        '\d+\.{0,1}\d*', list_)[1]
                                    result = float(result)

                                except:
                                    continue

                            # Appling re to find the number after a certain word
                            # Result is the number we need (VERY IMPORTANT)
                            else:
                                list_ = list(i.split())
                                list_ = str(list_)
                                try:
                                    result = re.search(
                                        '\d+\.{0,1}\d*', list_).group()
                                    result = float(result)

                                except:
                                    continue

                            custom_values_list.append(result)

            model_hba1c = joblib.load(
                "DocTork-master/ML_Model/API_2/PDF/Diabetes/Model/HbA1c.h5")
            model_fpg = joblib.load("DocTork-master/ML_Model/API_2/PDF/Diabetes/Model/FPG.h5")
            model_2hrpp = joblib.load(
                "DocTork-master/ML_Model/API_2/PDF/Diabetes/Model/HrPP.h5")
            faatures_hbalc = list(model_hba1c.feature_names_in_)
            faatures_fpg = list(model_fpg.feature_names_in_)
            faatures_2hrpp = list(model_2hrpp.feature_names_in_)
            features = faatures_hbalc + faatures_fpg + faatures_2hrpp
            features.pop(1)
            features.pop(2)
            custom_data = pd.DataFrame(data=np.array(
                [custom_values_list]), columns=features[:-1])
            custom_data['Gender'] = np.random.choice([1, 0])
            pred_hbalc = model_hba1c.predict(
                custom_data[list(model_hba1c.feature_names_in_)])[0]
            pred_fpg = model_fpg.predict(
                custom_data[list(model_fpg.feature_names_in_)])[0]
            pred_2hrr = model_2hrpp.predict(
                custom_data[list(model_2hrpp.feature_names_in_)])[0]
            # Model Output Meaning :
            # 0 >> Normal
            # 1 >> Diabetic
            # 2 >> Prediabetic
            # 3 >> Hypoglycemia

            if pred_hbalc == 1:
                output = 'Diabetic'

            elif (pred_hbalc == 0) and (pred_fpg == 1) and (pred_2hrr == 1):
                output = 'Diabetic'

            elif (pred_hbalc == 2) and (pred_fpg == 1) and (pred_2hrr == 1):
                output = 'Diabetic'

            elif (pred_hbalc == 2) and (pred_fpg == 2):
                output = 'Pre Diabetic'

            elif (pred_hbalc == 2) and (pred_fpg == 0):
                output = 'Pre Diabetic'

            elif (pred_hbalc == 0) and (pred_fpg == 2):
                output = 'Pre Diabetic'

            elif (pred_hbalc == 0) and (pred_fpg == 0):
                output = 'Normal'
            correct_predication_name = {
                'Anemia': 'Normal Anemia',
                'Good': 'Normal ',
                'Micro': 'Microcytic Anemia',
                'Macro': 'Macrocytic Anemia',
                'CML': 'Chronic Myelogenous Leukemia',
                'Acute L': 'Acute Lymphoblastic Leukemia',
                'HyperTyroid':  'Hyperthyroidism',
                'Hypothyroid': 'Hypothyroidism',
                'Other Thyroid Abnormalities':  'Other Thyroid Abnormalities',
                'Normal':  'Normal ',
                'Hyperuricosuria (Gout)': 'Hyperuricemia (Gout)',
                'Hypouricosuria ':  'Hypouricemia',
                'Jaundice':  'Jaundice',
                'Diabetic': 'Diabetes',
                'Pre Diabetic': 'Prediabetes',
                'Hypoglycemia': 'Hypoglycemia',
                'Prostatic_Cancer':  'Prostatic Cancer',
                'Rheumatiod_Arthities': 'Rheumatoid Arthritis',
                'Hypoparathyroid': 'Hypoparathyroidism',
                'Another Disease':  'Another Disease',
                'Hyperparathyroid': 'Hyperparathyroidism',
                'Acute  L or CML':  'Acute Lymphoblastic Lekumia and Chronic Myelogenous Lekumia',
                'Good':  'Normal',
                'Normal': 'Normal'}

            patient_output_disease = correct_predication_name[output]
            return patient_output_disease            

        except:
            custom_values_list = []
            for x in keywords:
                # ourpdf
                # Parsing the content of our pdf into a list of sentences
                rawText1 = parser.from_file(pdf)
                rawList1 = rawText1['content'].splitlines()
                # Iterating inside the list of sentences
                for i in rawList1:
                    i = i.replace(' ', '')
                    if re.search(x, i, re.IGNORECASE):
                        # Our chosen sentence
                        # Converting our little sentence to a list and splitting it into words to finally extract the needed number.
                        if ('A1C' in x) or ('HRPP' in x):

                            list_ = list(i.split())
                            list_ = str(list_)
                            try:
                                result = re.findall('\d+\.{0,1}\d*', list_)[1]
                                result = float(result)

                            except:
                                continue

                        # Appling re to find the number after a certain word
                        # Result is the number we need (VERY IMPORTANT)
                        else:
                            list_ = list(i.split())
                            list_ = str(list_)
                            try:
                                result = re.search(
                                    '\d+\.{0,1}\d*', list_).group()
                                result = float(result)

                            except:
                                continue

                        custom_values_list.append(result)

            model_hba1c = joblib.load(
                "DocTork-master/ML_Model/API_2/PDF/Diabetes/Model/HbA1c.h5")
            model_fpg = joblib.load("DocTork-master/ML_Model/API_2/PDF/Diabetes/Model/FPG.h5")
            model_2hrpp = joblib.load(
                "DocTork-master/ML_Model/API_2/PDF/Diabetes/Model/HrPP.h5")
            faatures_hbalc = list(model_hba1c.feature_names_in_)
            faatures_fpg = list(model_fpg.feature_names_in_)
            faatures_2hrpp = list(model_2hrpp.feature_names_in_)
            features = faatures_hbalc + faatures_fpg + faatures_2hrpp
            features.pop(1)
            features.pop(2)
            custom_data = pd.DataFrame(data=np.array(
                [custom_values_list]), columns=features[:-1])
            custom_data['Gender'] = np.random.choice([1, 0])
            pred_hbalc = model_hba1c.predict(
                custom_data[list(model_hba1c.feature_names_in_)])[0]
            pred_fpg = model_fpg.predict(
                custom_data[list(model_fpg.feature_names_in_)])[0]
            # pred_2hrr = model_2hrpp.predict(custom_data[list(model_2hrpp.feature_names_in_)])[0]
            # Model Output Meaning :
            # 0 >> Normal
            # 1 >> Diabetic
            # 2 >> Prediabetic
            # 3 >> Hypoglycemia

            if pred_hbalc == 1:
                output = 'Diabetic'

            elif (pred_hbalc == 0) and (pred_fpg == 1) and (pred_2hrr == 1):
                output = 'Diabetic'

            elif (pred_hbalc == 2) and (pred_fpg == 1) and (pred_2hrr == 1):
                output = 'Diabetic'

            elif (pred_hbalc == 2) and (pred_fpg == 2):
                output = 'Pre Diabetic'

            elif (pred_hbalc == 2) and (pred_fpg == 0):
                output = 'Pre Diabetic'

            elif (pred_hbalc == 0) and (pred_fpg == 2):
                output = 'Pre Diabetic'

            elif (pred_hbalc == 0) and (pred_fpg == 0):
                output = 'Normal'

            correct_predication_name = {
                'Anemia': 'Normal Anemia',
                'Good': 'Normal ',
                'Micro': 'Microcytic Anemia',
                'Macro': 'Macrocytic Anemia',
                'CML': 'Chronic Myelogenous Leukemia',
                'Acute L': 'Acute Lymphoblastic Leukemia',
                'HyperTyroid':  'Hyperthyroidism',
                'Hypothyroid': 'Hypothyroidism',
                'Other Thyroid Abnormalities':  'Other Thyroid Abnormalities',
                'Normal':  'Normal ',
                'Hyperuricosuria (Gout)': 'Hyperuricemia (Gout)',
                'Hypouricosuria ':  'Hypouricemia',
                'Jaundice':  'Jaundice',
                'Diabetic': 'Diabetes',
                'Pre Diabetic': 'Prediabetes',
                'Hypoglycemia': 'Hypoglycemia',
                'Prostatic_Cancer':  'Prostatic Cancer',
                'Rheumatiod_Arthities': 'Rheumatoid Arthritis',
                'Hypoparathyroid': 'Hypoparathyroidism',
                'Another Disease':  'Another Disease',
                'Hyperparathyroid': 'Hyperparathyroidism',
                'Acute  L or CML':  'Acute Lymphoblastic Lekumia and Chronic Myelogenous Lekumia',
                'Good':  'Normal',
                'Normal': 'Normal'}

            patient_output_disease = correct_predication_name[output]
            return patient_output_disease

    except:
        model_hba1c = joblib.load(
            "DocTork-master/ML_Model/API_2/PDF/Diabetes/Model/HbA1c.h5")
        model_fpg = joblib.load("DocTork-master/ML_Model/API_2/PDF/Diabetes/Model/FPG.h5")
        model_2hrpp = joblib.load(
            "DocTork-master/ML_Model/API_2/PDF/Diabetes/Model/HrPP.h5")
        faatures_hbalc = list(model_hba1c.feature_names_in_)
        faatures_fpg = list(model_fpg.feature_names_in_)
        faatures_2hrpp = list(model_2hrpp.feature_names_in_)
        features = faatures_hbalc + faatures_fpg + faatures_2hrpp
        features.pop(1)
        features.pop(2)
        return 'Your uploaded PDF can\'t be detected \n \t Enter Manually the Following Please : ', features[:-1]
