# -*- coding: utf-8 -*-
"""lekmuia_manual

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-lXFSx-rTmFClJ2XkECCFX21dZ4r7MdT
"""

import joblib
import pandas as pd
import numpy as np


def predict_manual(custom_values_list):
    model_acute_l = joblib.load(
        'ML_Model/API_2/Manual/Leukemia/Model/RandomForestModel(AcuteL-m,f).h5')
    model_cml = joblib.load(
        'ML_Model/API_2/Manual/Leukemia/Model/RandomForestModel(CML-m,f).h5')
    features = list(model_acute_l.feature_names_in_) + \
        list(model_cml.feature_names_in_)
    features.pop(3)  # Delete Duplicated Gender_Male from Feature List
    features.pop(3)  # Delete Duplicated Hemoglobin from Feature List
    features.pop(3)  # Delete Duplicated Platelets from Feature List
    print(features)
    custom_data = pd.DataFrame(data=np.array(
        [custom_values_list]), columns=features[:-1])
    custom_data['Gender_Male'] = np.random.choice([1, 0])
    pred_acute_l = model_acute_l.predict(
        custom_data[list(model_acute_l.feature_names_in_)])[0]
    pred_cml = model_cml.predict(
        custom_data[list(model_cml.feature_names_in_)])[0]
    if pred_cml == pred_acute_l:
        # As predication of two models is same
        # Two models have predicted Good as Label
        output = 'Good'
    elif pred_cml == 'CML' and pred_acute_l == 'Acute L':
        # As predication of two models is different
        # One model has predicted CML as Label
        # Other model has  predicted Acute L as Label
        output = 'Acute  L or CML'
    elif pred_cml == 'CML' and pred_acute_l == 'Good':
        # As predication of two models is different
        # One model has predicted CML as Label
        # Other model has  predicted Good as Label
        output = pred_cml
    elif pred_cml == 'Good' and pred_acute_l == 'Acute L':
        # As predication of two models is different
        # One model has predicted Good as Label
        # Other model has  predicted Acute L as Label
        output = 'Acute L'

    correct_predication_name = {
        'Anemia': 'Normal Anemia',
        'Good': 'Normal ',
        'Micro': 'Microcytic Anemia',
        'Macro': 'Macrocytic Anemia',
        'CML': 'Chronic Myelogenous Leukemia',
        'Acute L': 'Acute Lymphoblastic Leukemia',
        'HyperTyroid':  'Hyperthyroidism',
        'Hypothyroid': 'Hypothyroidism',
        'Other Thyroid Abnormalities':  'Other Thyroid Abnormalities',
        'Normal':  'Normal ',
        'Hyperuricosuria (Gout)': 'Hyperuricemia (Gout)',
        'Hypouricosuria ':  'Hypouricemia',
        'Jaundice':  'Jaundice',
        'Diabetic': 'Diabetes',
        'Pre Diabetic': 'Prediabetes',
        'Hypoglycemia': 'Hypoglycemia',
        'Prostatic_Cancer':  'Prostatic Cancer',
        'Rheumatiod_Arthities': 'Rheumatoid Arthritis',
        'Hypoparathyroid': 'Hypoparathyroidism',
        'Another Disease':  'Another Disease',
        'Hyperparathyroid': 'Hyperparathyroidism',
        'Acute  L or CML':  'Acute Lymphoblastic Lekumia and Chronic Myelogenous Lekumia',
        'Good':  'Normal',
        'Normal': 'Normal'}

    patient_output_disease = correct_predication_name[output]
    return patient_output_disease

# predict_manual([15,200000,190000,1,2])
